# Generated by Django 3.2 on 2021-04-19 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('construction', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('amount', models.FloatField()),
                ('trans_method', models.CharField(choices=[('Online Payment', 'Online Payment'), ('Hard Cash', 'Hard Cash')], max_length=100)),
                ('trans_date', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField()),
                ('trans_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Construction_Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Halted', 'Halted'), ('Completed', 'Completed')], max_length=50)),
                ('superviser', models.ManyToManyField(to='construction.Site_User')),
            ],
        ),
    ]
