# Generated by Django 3.2 on 2021-04-19 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_rename_status_transaction_conformation_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='conformation_status',
            new_name='confirmation_status',
        ),
    ]
