# Generated by Django 3.2 on 2021-04-20 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_rename_conformation_status_transaction_confirmation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='site_user',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_images/'),
        ),
    ]
