# Generated by Django 3.2 on 2021-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_site_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_site',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
