# Generated by Django 3.2 on 2021-05-08 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0007_transaction_trans_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.construction_site'),
        ),
    ]
