# Generated by Django 3.2 on 2021-05-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0008_alter_transaction_trans_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trans_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='construction.site_user'),
        ),
    ]
