# Generated by Django 3.2 on 2021-05-12 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0010_alter_site_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction_site',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='construction_site',
            name='expensed',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='construction_site',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='site_profiles/'),
        ),
        migrations.AddField(
            model_name='construction_site',
            name='num_workers',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
