# Generated by Django 3.2 on 2021-05-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0011_auto_20210512_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='construction_site',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
