# Generated by Django 3.2 on 2021-05-12 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0012_construction_site_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction_site',
            name='superviser',
        ),
        migrations.AddField(
            model_name='construction_site',
            name='superviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.site_user'),
        ),
    ]
