# Generated by Django 3.2 on 2021-05-12 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0014_auto_20210512_1831'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site_user',
            old_name='username',
            new_name='name',
        ),
    ]
