# Generated by Django 3.2 on 2021-05-12 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0015_rename_username_site_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='trans_type',
            field=models.CharField(blank=True, choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=50, null=True),
        ),
    ]
