# Generated by Django 3.2 on 2021-06-25 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0016_transaction_trans_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='construction_site',
            name='superviser',
        ),
        migrations.AddField(
            model_name='site_user',
            name='site_supervising',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.construction_site'),
        ),
    ]
