# Generated by Django 3.2 on 2021-06-25 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0017_auto_20210625_0933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site_user',
            name='site_supervising',
        ),
        migrations.AddField(
            model_name='construction_site',
            name='superviser',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.site_user'),
        ),
    ]
