# Generated by Django 3.2.4 on 2021-07-01 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0018_auto_20210625_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transactionimages/'),
        ),
    ]
