# Generated by Django 3.2.4 on 2021-10-05 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0020_workerattendence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='workerimages/')),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='workerattendence',
            name='name',
        ),
        migrations.AddField(
            model_name='workerattendence',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='workerattendence',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.worker'),
        ),
    ]
