# Generated by Django 3.2.4 on 2021-10-07 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0021_auto_20211005_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerattendence',
            name='worker',
        ),
        migrations.AddField(
            model_name='workerattendence',
            name='worker',
            field=models.ManyToManyField(null=True, to='construction.Worker'),
        ),
    ]
