# Generated by Django 3.2.4 on 2021-10-07 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0022_auto_20211007_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerattendence',
            name='worker',
        ),
        migrations.AddField(
            model_name='workerattendence',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.worker'),
        ),
    ]
