# Generated by Django 3.2.4 on 2021-10-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0023_auto_20211007_1119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerattendence',
            name='worker',
        ),
        migrations.AddField(
            model_name='workerattendence',
            name='worker',
            field=models.ManyToManyField(null=True, to='construction.Worker'),
        ),
    ]
