# Generated by Django 3.2.4 on 2021-10-07 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0024_auto_20211007_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerattendence',
            name='worker',
        ),
        migrations.AddField(
            model_name='worker',
            name='attendence',
            field=models.ManyToManyField(null=True, to='construction.WorkerAttendence'),
        ),
        migrations.AddField(
            model_name='workerattendence',
            name='workerss',
            field=models.ManyToManyField(null=True, to='construction.Worker'),
        ),
    ]
