# Generated by Django 3.2.4 on 2021-10-07 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0025_auto_20211007_1136'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workerattendence',
            old_name='workerss',
            new_name='worker',
        ),
        migrations.RemoveField(
            model_name='worker',
            name='attendence',
        ),
    ]
