# Generated by Django 3.2.4 on 2021-10-11 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0026_auto_20211007_1201'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendenceReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_labour', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.worker')),
            ],
        ),
        migrations.CreateModel(
            name='On_Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('worker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.worker')),
            ],
        ),
        migrations.DeleteModel(
            name='WorkerAttendence',
        ),
        migrations.AddField(
            model_name='attendencereport',
            name='duty_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.on_duty'),
        ),
        migrations.AddField(
            model_name='attendencereport',
            name='leave_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.leave'),
        ),
        migrations.AddField(
            model_name='attendencereport',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.worker'),
        ),
    ]
