# Generated by Django 3.2.4 on 2021-10-11 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0029_auto_20211011_1036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendencereport',
            name='worker',
        ),
        migrations.AlterField(
            model_name='attendencereport',
            name='leave_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.leave'),
        ),
    ]
