# Generated by Django 3.2.4 on 2021-10-11 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0030_auto_20211011_1103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendencereport',
            name='total_labour',
        ),
    ]
