# Generated by Django 3.2.4 on 2021-10-11 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0032_auto_20211011_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='on_duty',
            name='worker',
        ),
        migrations.RemoveField(
            model_name='attendencereport',
            name='duty_id',
        ),
        migrations.RemoveField(
            model_name='attendencereport',
            name='leave_id',
        ),
        migrations.AddField(
            model_name='attendencereport',
            name='present',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendencereport',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.construction_site'),
        ),
        migrations.AddField(
            model_name='attendencereport',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='construction.worker'),
        ),
        migrations.DeleteModel(
            name='Leave',
        ),
        migrations.DeleteModel(
            name='On_Duty',
        ),
    ]
